"""add invoice cancellation model

Revision ID: 24fe85ab2bd0
Revises: 5e3b8935fbbd
Create Date: 2026-07-25 12:48:21.253048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '24fe85ab2bd0'
down_revision: Union[str, Sequence[str], None] = '5e3b8935fbbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_items', sa.Column('reversed_invoice_item_id', sa.Integer(), nullable=True))
    op.alter_column('invoice_items', 'charging_session_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_unique_constraint(None, 'invoice_items', ['reversed_invoice_item_id'])
    op.create_foreign_key(None, 'invoice_items', 'invoice_items', ['reversed_invoice_item_id'], ['id'], ondelete='RESTRICT')
    op.add_column('invoices', sa.Column('document_type', sa.String(length=20), server_default='invoice', nullable=False))
    op.add_column('invoices', sa.Column('cancellation_reason', sa.String(length=500), nullable=True))
    op.add_column('invoices', sa.Column('cancelled_at', sa.DateTime(), nullable=True))
    op.add_column('invoices', sa.Column('original_invoice_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'invoices', ['original_invoice_id'])
    op.create_foreign_key(None, 'invoices', 'invoices', ['original_invoice_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='unique')
    op.drop_column('invoices', 'original_invoice_id')
    op.drop_column('invoices', 'cancelled_at')
    op.drop_column('invoices', 'cancellation_reason')
    op.drop_column('invoices', 'document_type')
    op.drop_constraint(None, 'invoice_items', type_='foreignkey')
    op.drop_constraint(None, 'invoice_items', type_='unique')
    op.alter_column('invoice_items', 'charging_session_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('invoice_items', 'reversed_invoice_item_id')
    # ### end Alembic commands ###
