"""add xlsx import support

Revision ID: 39731804bff0
Revises: 3acf2243df37
Create Date: 2026-07-22 14:47:33.532852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '39731804bff0'
down_revision: Union[str, Sequence[str], None] = '3acf2243df37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charging_sessions', sa.Column('import_hash', sa.String(length=64), nullable=True))
    op.add_column('charging_sessions', sa.Column('source', sa.String(length=20), nullable=False))
    op.alter_column('charging_sessions', 'hager_session_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.create_unique_constraint(None, 'charging_sessions', ['import_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'charging_sessions', type_='unique')
    op.alter_column('charging_sessions', 'hager_session_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_column('charging_sessions', 'source')
    op.drop_column('charging_sessions', 'import_hash')
    # ### end Alembic commands ###
