"""add accounting data model

Revision ID: 3acf2243df37
Revises: 820ff931c037
Create Date: 2026-07-19 15:25:09.742404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3acf2243df37'
down_revision: Union[str, Sequence[str], None] = '820ff931c037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energy_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('grid_price_net', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('pv_price_net', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('salutation', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('invoice_delivery_email', sa.Boolean(), nullable=False),
    sa.Column('invoice_delivery_post', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('rfid_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rfid_number', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rfid_number')
    )
    op.create_table('charging_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hager_session_id', sa.String(length=100), nullable=False),
    sa.Column('station_id', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('rfid_card_id', sa.Integer(), nullable=True),
    sa.Column('energy_total_kwh', sa.Float(), nullable=False),
    sa.Column('energy_pv_kwh', sa.Float(), nullable=False),
    sa.Column('cost_grid_net', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cost_pv_net', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('invoiced', sa.Boolean(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rfid_card_id'], ['rfid_cards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hager_session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('charging_sessions')
    op.drop_table('rfid_cards')
    op.drop_table('users')
    op.drop_table('energy_prices')
    # ### end Alembic commands ###
