"""add invoice party snapshots

Revision ID: 73094676afbc
Revises: aa90256e6ae6
Create Date: 2026-07-24 09:38:13.707957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73094676afbc'
down_revision: Union[str, Sequence[str], None] = 'aa90256e6ae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('issuer_name', sa.String(length=255), nullable=False))
    op.add_column('invoices', sa.Column('issuer_address', sa.String(length=500), nullable=False))
    op.add_column('invoices', sa.Column('issuer_tax_number', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('issuer_vat_id', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('recipient_name', sa.String(length=255), nullable=False))
    op.add_column('invoices', sa.Column('recipient_address', sa.String(length=500), nullable=False))
    op.add_column(
        "invoices",
        sa.Column(
            "pdf_storage_path",
            sa.String(length=500),
            nullable=True,
        ),
    )
    op.add_column(
        "invoices",
        sa.Column(
            "pdf_sha256",
            sa.String(length=64),
            nullable=True,
        ),
    )
    op.add_column(
        "invoices",
        sa.Column(
            "pdf_size_bytes",
            sa.Integer(),
            nullable=True,
        ),
    )
    op.add_column(
        "invoices",
        sa.Column(
            "pdf_created_at",
            sa.DateTime(),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'recipient_address')
    op.drop_column('invoices', 'recipient_name')
    op.drop_column('invoices', 'issuer_vat_id')
    op.drop_column('invoices', 'issuer_tax_number')
    op.drop_column('invoices', 'issuer_address')
    op.drop_column('invoices', 'issuer_name')
    op.drop_column(
        "invoices",
        "pdf_created_at",
    )
    op.drop_column(
        "invoices",
        "pdf_size_bytes",
    )
    op.drop_column(
        "invoices",
        "pdf_sha256",
    )
    op.drop_column(
        "invoices",
        "pdf_storage_path",
    )
    # ### end Alembic commands ###
