"""add invoices and invoice items

Revision ID: aa90256e6ae6
Revises: 1854f1182952
Create Date: 2026-07-23 22:54:28.821854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa90256e6ae6'
down_revision: Union[str, Sequence[str], None] = '1854f1182952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('service_period_start', sa.DateTime(), nullable=False),
    sa.Column('service_period_end', sa.DateTime(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='EUR', nullable=False),
    sa.Column('total_net', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('total_gross', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index(op.f('ix_invoices_user_id'), 'invoices', ['user_id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('charging_session_id', sa.Integer(), nullable=False),
    sa.Column('position_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('session_start', sa.DateTime(), nullable=False),
    sa.Column('session_end', sa.DateTime(), nullable=False),
    sa.Column('station_id', sa.String(length=255), nullable=False),
    sa.Column('energy_total_kwh', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('energy_grid_kwh', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('energy_pv_kwh', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('grid_price_net', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('pv_price_net', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('cost_grid_net', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('cost_pv_net', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['charging_session_id'], ['charging_sessions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('charging_session_id'),
    sa.UniqueConstraint(
        "invoice_id",
        "position_number",
        name="uq_invoice_items_invoice_position",
    ),
    )
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_invoices_user_id'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
